# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('note', models.TextField(blank=True, verbose_name='正文')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('online_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上线时间')),
                ('offline_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下线时间')),
                ('open_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开奖时间')),
                ('option', models.BooleanField(default=False, verbose_name='开奖选项')),
                ('status', models.BooleanField(default=False, verbose_name='开奖状态')),
                ('settlement', models.BooleanField(default=False, verbose_name='已结算')),
            ],
            options={
                'verbose_name': 'M - 竞猜列表',
                'verbose_name_plural': 'M - 竞猜列表',
            },
        ),
        migrations.CreateModel(
            name='BetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='竞猜分类')),
            ],
            options={
                'verbose_name': 'M - 竞猜分类',
                'verbose_name_plural': 'M - 竞猜分类',
            },
        ),
        migrations.CreateModel(
            name='BetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('option', models.BooleanField(default=False, verbose_name='YES')),
                ('backAmount', models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='回款数量')),
            ],
            options={
                'verbose_name': '下注列表',
                'verbose_name_plural': '下注列表',
            },
        ),
        migrations.CreateModel(
            name='PaymentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=34, unique=True, verbose_name='钱包地址')),
                ('account', models.CharField(max_length=100, verbose_name='钱包账户')),
                ('privkey', models.CharField(max_length=256, verbose_name='钱包私钥')),
            ],
            options={
                'verbose_name': '钱包地址',
                'verbose_name_plural': '钱包地址',
            },
        ),
        migrations.CreateModel(
            name='PaymentBackAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=34, unique=True, verbose_name='钱包地址')),
            ],
            options={
                'verbose_name': '回款钱包地址',
                'verbose_name_plural': '回款钱包地址',
            },
        ),
        migrations.CreateModel(
            name='PaymentBackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True, verbose_name='txid')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='交易量')),
                ('confirmations', models.IntegerField(default=0, verbose_name='确认次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.PaymentBackAddress', verbose_name='地址')),
            ],
            options={
                'verbose_name': '回款钱包日志',
                'verbose_name_plural': '回款钱包日志',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True, verbose_name='txid')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='交易量')),
                ('confirmations', models.IntegerField(default=0, verbose_name='确认次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.BetLog', verbose_name='地址')),
            ],
            options={
                'verbose_name': '收款钱包日志',
                'verbose_name_plural': '收款钱包日志',
            },
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpc_address', models.CharField(max_length=255, verbose_name='RPC地址')),
                ('rpc_port', models.CharField(max_length=255, verbose_name='RPC端口')),
                ('rpc_username', models.CharField(max_length=255, verbose_name='RPC用户')),
                ('rpc_password', models.CharField(max_length=255, verbose_name='RPC密码')),
                ('rpc_settxfee', models.DecimalField(decimal_places=8, default=0.0007, max_digits=16, verbose_name='交易费')),
            ],
            options={
                'verbose_name': 'M - RPC钱包设置',
                'verbose_name_plural': 'M - RPC钱包设置',
            },
        ),
        migrations.AddField(
            model_name='betlog',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.PaymentAddress', verbose_name='收款地址'),
        ),
        migrations.AddField(
            model_name='betlog',
            name='backAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.PaymentBackAddress', verbose_name='回款地址'),
        ),
        migrations.AddField(
            model_name='betlog',
            name='bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bet.Bet', verbose_name='竞猜ID'),
        ),
        migrations.AddField(
            model_name='bet',
            name='betClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bet.BetClass', verbose_name='竞猜分类'),
        ),
    ]
