# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentaddress',
            options={'verbose_name': '收款钱包地址', 'verbose_name_plural': '收款钱包地址'},
        ),
    ]
