# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_auto_20160810_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbacklog',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='矿工费'),
        ),
    ]
