# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_remove_betlog_backamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentoption',
            name='rpc_settxfee',
        ),
    ]
