# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0005_remove_paymentoption_rpc_settxfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='open_time',
        ),
    ]
